export default {
  fontFamily: 'Roboto, Arial, sans-serif',
  defaultLocale: 'en',
  locales: [
    {
      name: 'en',
      options: {
        months: [
          'January',
          'February',
          'March',
          'April',
          'May',
          'June',
          'July',
          'August',
          'September',
          'October',
          'November',
          'December',
        ],
        shortMonths: [
          'Jan',
          'February',
          'Mar',
          'Apr',
          'May',
          'Jun',
          'Jul',
          'Aug',
          'Sep',
          'Oct',
          'Nov',
          'Dec',
        ],
        days: [
          'Sunday',
          'Monday',
          'Tuesday',
          'Wednesday',
          'Thursday',
          'Friday',
          'Saturday',
        ],
        shortDays: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
        toolbar: {
          download: 'Tải ảnh SVG',
          selection: 'Selection',
          selectionZoom: 'Chế độ thu phóng',
          zoomIn: 'Phóng to',
          zoomOut: 'Thu nhỏ',
          pan: 'Chế dộ xoay',
          reset: 'Thu phóng mặc định',
        },
      },
    },
  ],
}
